import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "@/contexts/cart.context";
import ClientLayout from "@/components/ClientLayout";
import { Inter, Genos } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const genos = Genos({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-genos",
});
export const metadata: Metadata = {
  title: "Orbis",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  ${genos.variable} antialiased min-h-screen flex flex-col relative bg-[#070913]`}
      >
        <div className="relative z-10 flex-1 flex flex-col">
          <CartProvider>
            <ClientLayout>{children}</ClientLayout>
          </CartProvider>
        </div>
      </body>
    </html>
  );
}
