import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "@/contexts/cart.context";
import ClientLayout from "@/components/ClientLayout";
// ИСПРАВЛЕНО: Добавили Anta в общий импорт шрифтов Google
import { Inter, Genos, Anta } from "next/font/google"; 

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const genos = Genos({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-genos",
});

// ИСПРАВЛЕНО: Инициализируем шрифт Anta (weight: 400 подтягивается автоматически)
const anta = Anta({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-anta",
});

export const metadata: Metadata = {
  title: "Orbis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        /* ИСПРАВЛЕНО: Убран хак-скрипт из head, а в className добавлена переменная ${anta.variable} */
        className={`${inter.variable} ${genos.variable} ${anta.variable} antialiased min-h-screen flex flex-col relative bg-[#070913]`}
      >
        <div className="relative z-10 flex-1 flex flex-col">
          <CartProvider>
            <ClientLayout>{children}</ClientLayout>
          </CartProvider>
        </div>
      </body>
    </html>
  );
}